# GET http://localhost:9000/api/ HTTP/1.1

POST http://localhost:9000/api/signup HTTP/1.1
content-type: application/json

{
    "email": "test03@test.com",
    "password":"0123456789",
    "favorite_color": "black",
    "favorite_animal": "crow"
}

